# Generated by Django 6.0 on 2026-01-21 12:57

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(default=datetime.date.today)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(help_text='Hotel this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('hotel', 'snapshot_date')},
            },
            managers=[
                ('objects', core.models.HotelScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(help_text='Hotel this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('hotel', 'year', 'month')},
            },
            managers=[
                ('objects', core.models.HotelScopedManager()),
            ],
        ),
    ]
