# Generated by Django 6.0 on 2026-01-21 12:57

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_mobile', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^[0-9+\\-\\s]{8,20}$')])),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveIntegerField(default=0)),
                ('with_food', models.BooleanField(default=False)),
                ('extra_bed', models.BooleanField(default=False)),
                ('early_check_in_option', models.CharField(blank=True, choices=[('5-7', '5:00 AM to 7:00 AM'), ('7-9', 'Above 7:00 AM to 9:00 AM'), ('9-11', 'Above 9:00 AM to 11:00 AM')], max_length=16)),
                ('late_check_out_option', models.CharField(blank=True, choices=[('11-13', '11:00 AM to 1:00 PM'), ('13-15', 'Above 1:00 PM to 3:00 PM'), ('15-17', 'Above 3:00 PM to 5:00 PM')], max_length=16)),
                ('special_request', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow Up'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='Hotel this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='hotels.roomcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', core.models.HotelScopedManager()),
            ],
        ),
    ]
