# Generated by Django 6.0 on 2026-01-21 12:57

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking')),
                ('hotel', models.ForeignKey(help_text='Hotel this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
            managers=[
                ('objects', core.models.HotelScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='DDL', max_length=32)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequence', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Invoice sequence',
                'verbose_name_plural': 'Invoice sequences',
            },
        ),
    ]
