# Generated by Django 6.0 on 2026-01-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesequence',
            name='prefix',
            field=models.CharField(default='DDI', max_length=32),
        ),
    ]
